package:
  name: sshtunnel
  version: "0.0.8"

source:
  git_url: https://github.com/Ohjeah/sshtunnel
  #git_tag: "0.0.8"
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sshtunnel = sshtunnel:main
    #
    # Would create an entry point called sshtunnel that calls sshtunnel.main()

    - sshtunnel=sshtunnel:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paramiko >=1.15.2

  run:
    - python
    - paramiko >=1.15.2

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - sshtunnel --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pahaz/sshtunnel
  license: MIT License
  summary: 'Pure python SSH tunnels'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
