package:
  name: sshtunnel
  version: "0.0.8"

source:
  git_url: https://github.com/pahaz/sshtunnel/
  git_tag: v008
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tqdm = tqdm:main
    #
    # Would create an entry point called tqdm that calls tqdm.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paramiko

  run:
    - paramiko

test:
  imports:
    - sshtunnel
