package:
  name: ffx
  version: "1.3.4"

source:
    git_url: https://github.com/natekupp/ffx


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - scikit-learn
    - numpy
    - scipy
test:
  # Python imports
  imports:
    - ffx
    - tests

about:
  home: https://github.com/natekupp/ffx
  license: See readme
  summary: 'Fast Function Extraction: A fast, scalable, and deterministic symbolic regression tool.'
