package:
  name: ffx
  version: "1.3.4"

source:
    git_url: https://github.com/Ohjeah/ffx


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - scikit-learn
    - numpy
    - scipy
    - pandas
test:

  imports:
    - sklearn
    - numpy
    - scipy
    - pandas
    - ffx
  files:
    - tests/

  requires:
    - nose

  commands:
    - nosetests ffx



about:
  home: https://github.com/natekupp/ffx
  license: See readme
  summary: 'Fast Function Extraction: A fast, scalable, and deterministic symbolic regression tool.'
