package:
  name: ecmwf-api-client
  version: "1.3"

source:
  fn: ecmwf-api-client-1.3.tar.gz
  url: https://pypi.python.org/packages/source/e/ecmwf-api-client/ecmwf-api-client-1.3.tar.gz
  md5: 4f5464629ad1b66ab3363dcabc17ff32
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ecmwf-api-client = ecmwf-api-client:main
    #
    # Would create an entry point called ecmwf-api-client that calls ecmwf-api-client.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ecmwfapi

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://software.ecmwf.int/stash/projects/PRDEL/repos/ecmwf-api-client/browse
  license: UNKNOWN
  summary: 'Python client for ECMWF web services API.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
